version: '3.3'

services:
  api:
    volumes:
      - ./app:/usr/src/app
    env_file:
      - app/app.dev.env

  frontend:
    ports:
      - '8080:8080'

  docs:
    volumes:
      - ./docs:/usr/src/app

  docs:
    build:
      dockerfile: docker/docs/Dockerfile
      context: ./
    image: catswhocode/docs:latest
    container_name: catswhocode_docs
    volumes:
      - ./docs:/usr/src/app
    ports:
      - '3000:8000'
    restart: on-failure

  portainer:
    image: portainer/portainer:latest
    container_name: catswhocode_portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '9000:9000'
    restart: on-failure
