version: '3.3'

services:
  api:
    command: './manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./app:/usr/src/app
    env_file:
      - app/app.dev.env

  frontend:
    ports:
      - '8080:8080'

  docs:
    volumes:
      - ./docs:/usr/src/app

  awslinux:
    volumes:
      - .:/usr/src/app

  awscli:
    volumes:
      - ./docker/awscli:/usr/src/app
