version: '3.3'

services:
  api:
    command: './manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./app:/usr/src/app
    environment:
      - DJANGO_DEBUG=True
  docs:
    volumes:
      - ./docs:/usr/src/app

  awslinux:
    volumes:
      - .:/usr/src/app

  awscli:
    volumes:
      - ./docker/awscli:/usr/src/app
