version: '3.3'

services:
  api:
    volumes:
      - ./app:/usr/src/app
    networks:
      - frontend
      - backend
    env_file:
      - app/app.dev.env

  frontend:
    ports:
      - '8080:8080'

  db:
    image: mysql:5.7
    container_name: catswhocode_db
    ports:
      - '3306:3306'
    networks:
      - backend
    restart: on-failure
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=True

  cache:
    image: redis:4-alpine
    container_name: catswhocode_cache
    ports:
      - '6379:6379'
    networks:
      - backend
    restart: on-failure

  docs:
    volumes:
      - ./docs:/usr/src/app

  docs:
    build:
      dockerfile: docker/docs/Dockerfile
      context: ./
    image: catswhocode/docs:latest
    container_name: catswhocode_docs
    volumes:
      - ./docs:/usr/src/app
    ports:
      - '3000:8000'
    restart: on-failure

  portainer:
    image: portainer/portainer:latest
    container_name: catswhocode_portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '9000:9000'
    restart: on-failure

networks:
  frontend:
  backend: