version: '3.3'

services:
  api:
    build:
      dockerfile: docker/api/Dockerfile
      context: ./
    image: catswhocode/api:latest
    container_name: catswhocode_api
    ports:
      - '8000'
    networks:
      - frontend
    restart: on-failure
    env_file:
      - app/app.prod.env

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./docker/frontend
    image: catswhocode/frontend:latest
    container_name: catswhocode_frontend
    ports:
      - '80:8080'
    depends_on:
      - api
    networks:
      - frontend
    restart: on-failure

networks:
  frontend:

