site_name: Cats Who Code Docs

theme: readthedocs

markdown_extensions:
    - toc:
        permalink: []
    - admonition:
    - markdown_newtab: 

pages:
- Home: 'index.md'
- Local Environment Setup: 'local-dev-setup.md'
- Running the App Locally: 'run-app-locally.md'

